spring:
  datasource:
    url: jdbc:mysql:///myapi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
sa-token:
  is-log: true
  # jwt秘钥
  jwt-secret-key: yUxlkvRqnscnGWnYgonR6eTty8dzyaEe